### ISSUE TITLE
GH Actions Markdown table should link to the specific commit in the table

### ISSUE THREAD

**Issue by philpax** [goatcorp/Plogon#19]
The commit hash here
![image](https://user-images.githubusercontent.com/707827/185771404-1282211d-b734-4069-9cf6-a2f8b5453458.png)
should be clickable and take you to the repo at the specified ref. (GH/GL only I would presume)

**Comment by goaaats** [comment]
Done with https://github.com/goatcorp/Plogon/commit/534ce0cbbcb134374f2f95513fa282f2293a5274
