### ISSUE TITLE
Plugins with the same version across channels result in an error

### ISSUE THREAD

**Issue by philpax** [goatcorp/Plogon#56]
https://github.com/goatcorp/DalamudPluginsD17/pull/3194#issuecomment-1946304913

> Build system error: Directory not empty : '/home/runner/work/DalamudPluginsD17/DalamudPluginsD17/work/SimpleMarketBoard-b3ad1092babf584bbe6ef2f81ed60e774da6d4a2-work'

From the word of goat:
> regression from a performance optimization I made for continuous builds

**Comment by goaaats** [comment]
https://github.com/goatcorp/Plogon/commit/cb8bed3e2c734a45f610941d2955456e76668123
