### ISSUE TITLE
C# 12 support

### ISSUE THREAD

**Issue by philpax** [goatcorp/Plogon#57]
https://github.com/goatcorp/DalamudPluginsD17/pull/3272 (at time of writing) uses C# 12 code (i.e. primary constructors). We don't currently have any other authors using C# 12, but I'm just making a note of this for future reference. Is this just a function of the version of .NET we build with?

**Comment by NotNite** [comment]
I fixed this months ago in #53. It has not been merged.

**Comment by goaaats** [comment]
We will only upgrade on the 15th together with .NET 8 support

**Comment by youssef-19** [comment]
nice

**Comment by philpax** [comment]
thank you Youssef for reminding me that this is done
